<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CheckRide</RootNamespace>
    <AssemblyName>CheckRide</AssemblyName>
    <ApplicationIcon>images\icon_256x256.ico</ApplicationIcon>
    <AssemblyTitle>CheckRide for SimLetsFly</AssemblyTitle>
    <Product>CheckRide for SimLetsFly</Product>
    <Company>SimLetsFly</Company>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="sounds\**\*.wav" />
    <EmbeddedResource Include="sounds\audio.txt" />
    <EmbeddedResource Include="samples\*.json" />
    <EmbeddedResource Include="samples\*.log" />
    <EmbeddedResource Include="images\*" />
    <EmbeddedResource Include="refdata\*" />
  </ItemGroup>
</Project>
